resources:
- name: repo
  type: git
  source:
    uri: https://github.com/making/hello-servlet.git
- name: cnb-on-concourse
  type: git
  source:
    uri: https://github.com/making/cnb-on-concourse.git
- name: builder
  type: docker-image
  source:
    repository: ((builder-image))
    tag: ((builder-tag))
jobs:
- name: pack-build
  plan:
  - in_parallel:
    - get: cnb-on-concourse
    - get: workspace
      resource: repo
    - get: builder
  - task: build
    image: builder
    file: cnb-on-concourse/tasks/pack-build.yml
    params:
      USE_CRED_HELPERS: false
      IMAGE: ((docker-image))
      DOCKER_REGISTRY: ((docker-registry))
      DOCKER_USERNAME: ((docker-username))
      DOCKER_PASSWORD: ((docker-password))
  - task: check-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      inputs:
      - name: image
      run:
        path: bash
        args: 
        - -c
        - |
          echo "image: ((docker-image))@sha256:$(cat image/digest)"
