---
platform: linux
inputs:
- name: workspace
caches:
- path: layers
- path: cache
outputs:
- name: image
params:
  IMAGE: 
  USE_CRED_HELPERS: false
  DOCKER_REGISTRY: index.docker.io
  DOCKER_USERNAME: ""
  DOCKER_PASSWORD: ""
  CNB_REGISTRY_AUTH: ""
run:
  user: root
  path: bash
  args: 
  - -c
  - |
    set -eo pipefail

    rm -rf /layers
    rm -rf /workspace
    rm -rf /cache

    ln -fs $(pwd)/layers/ /layers
    ln -fs $(pwd)/workspace/ /workspace
    ln -fs $(pwd)/workspace/ /cache

    if [ "${CNB_REGISTRY_AUTH}" = "" ];then
      export CNB_REGISTRY_AUTH="{\"${DOCKER_REGISTRY}\":\"Basic $(echo -n ${DOCKER_USERNAME}:${DOCKER_PASSWORD} | base64)\"}"
    fi

    echo "===> DETECTING"
    /lifecycle/detector \
      -app=/workspace \
      -group=/layers/group.toml \
      -plan=/layers/plan.toml

    echo "===> RESTORING"
    /lifecycle/restorer \
      -group=/layers/group.toml \
      -layers=/layers \
      -path=/cache

    echo "===> ANALYZING"
    /lifecycle/analyzer \
      -layers=/layers \
      -helpers=${USE_CRED_HELPERS} \
      -group=/layers/group.toml \
      ${IMAGE}

    echo "===> BUILDING"
    /lifecycle/builder \
      -app=/workspace \
      -layers=/layers \
      -group=/layers/group.toml \
      -plan=/layers/plan.toml

    echo "===> EXPORTING"
    /lifecycle/exporter \
      -app=/workspace \
      -layers=/layers \
      -helpers=${USE_CRED_HELPERS} \
      -group=/layers/group.toml \
      ${IMAGE} | tee export.log

    DIGEST=$(grep ' Digest:' export.log | grep 'Digest' | sed 's/.*Digest: sha256://')

    echo "===> CACHING"
    rm -rf /cache/*
    /lifecycle/cacher \
      -group=/layers/group.toml \
      -path=/cache

    echo "${DIGEST}" >> ./image/digest
    echo "sha256:${DIGEST}" >> ./image/image-id